version: '3.7'
services:
  metadatadb:
    container_name: tyre_wear-metadadb
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: tfx
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: tfx_metadata
    ports:
      - "3306:3306"
  airflow:
    container_name: tf_sample_model-airflow
#   depends_on: [metadatadb]
    image: eu.gcr.io/kubeflow-in-action/local-airflow:tfx-master
    init: true
    ports:
    - "8080:8080"
    environment:
    - GOOGLE_APPLICATION_CREDENTIALS=/secrets/creds.json
    - GCLOUD_PROJECT=renault-ml
    - MLFLOW_TRAKING_URI=/pipeline/mlruns
    volumes:
    - ./secrets:/secrets
    - tfxPipelineVolume:/pipeline
    - ./tf_sample_model:/airflow/dags/tf_sample_model
    - ./config:/airflow/dags
    entrypoint: /airflow/run_airflow.sh

  jupyter:
    container_name: tf_sample_model-jupyter
#   depends_on: [metadatadb]
    image: eu.gcr.io/kubeflow-in-action/tfx-jupyter:latest
    init: true
    ports:
      - "8081:8081"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/secrets/creds.json
      - GCLOUD_PROJECT=renault-ml
    volumes:
      - ./notebooks:/notebooks/custom
      - tfxPipelineVolume:/pipeline
      - ./secrets:/secrets
  mlflow:
    container_name: tf_sample_model-mlflow
    image: eu.gcr.io/kubeflow-in-action/mlflow:latest
    init: true
    ports:
      - "5000:5000"
    volumes:
      - tfxPipelineVolume:/mlflow
  tensorboard:
    container_name: tf_sample_model-tensorboard
    image: tensorflow/tensorflow:1.13.1
    init: true
    ports:
      - "6006:6006"
    volumes:
      - tfxPipelineVolume:/pipeline
    entrypoint: ["tensorboard", "--logdir", "/pipeline/tfx/tf-sample-model/tf-sample-model/Trainer/output"]

volumes:
  tfxPipelineVolume: {}
